server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        refresh-enabled: true
        enabled: true
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
        endpoint: 127.0.0.1:8848
#        extension-configs:
#          - data-id: user-service-datasource
#            group: datasource
#            refresh: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://rm-bp15h5a44683401mfso.mysql.rds.aliyuncs.com:3306/bbs-user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    username: zjlhyy
#spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp15h5a44683401mfso.mysql.rds.aliyuncs.com:3306/bbs-user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: zjlhyy
      password: Zjl10101028

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl